language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
script: ./gradlew build
